export const navData = [
  {
    link: "/",
    title: "Главная",
    bgColor: "bg-gray-100",
    textColor: "text-white",
    items: [],
  },
  {
    link: "services",
    title: "Услуги",
    bgColor: "bg-consulting",
    textColor: "text-consulting",
    items: [
      {
        link: "it-consulting",
        title: "ИТ-консалтинг",
        bgColor: "bg-consulting",
        textColor: "text-consulting",
        items: [
          {
            link: "it-audit",
            title: "ИТ-аудит",
            bgColor: "bg-consulting",
            textColor: "text-consulting",
            items: [],
          },
          {
            link: "it-audit",
            title: "Обслуживание серверов",
            bgColor: "bg-consulting",
            textColor: "text-consulting",
            items: [],
          },
          {
            link: "it-audit",
            title: "Специализированное ПО",
            bgColor: "bg-consulting",
            textColor: "text-consulting",
            items: [],
          },
          {
            link: "it-audit",
            title: "Техподдержка",
            bgColor: "bg-consulting",
            textColor: "text-consulting",
            items: [],
          },
          {
            link: "it-audit",
            title: "Обслуживание сетевого оборудования",
            bgColor: "bg-consulting",
            textColor: "text-consulting",
            items: [],
          },
          {
            link: "it-audit",
            title: "Обслуживание VOIP",
            bgColor: "bg-consulting",
            textColor: "text-consulting",
            items: [],
          },
          {
            link: "it-audit",
            title: "Оптимизация работы 1С",
            bgColor: "bg-consulting",
            textColor: "text-consulting",
            items: [],
          },
          {
            link: "it-audit",
            title: "Организация удалённой работы (VPN)",
            bgColor: "bg-consulting",
            textColor: "text-consulting",
            items: [],
          },
          {
            link: "it-audit",
            title: "Резервные копии в защищённое облако",
            bgColor: "bg-consulting",
            textColor: "text-consulting",
            items: [],
          },
          {
            link: "it-audit",
            title: "Резервное копирование",
            bgColor: "bg-consulting",
            textColor: "text-consulting",
            items: [],
          },
          {
            link: "it-audit",
            title: "Сервис Helpdesk",
            bgColor: "bg-consulting",
            textColor: "text-consulting",
            items: [],
          },
        ],
      },
      {
        link: "cloud-management",
        title: "Менеджмент облачной инфраструктуры",
        bgColor: "bg-cloud",
        textColor: "text-cloud",
        items: [],
      },
      {
        link: "it-security",
        title: "Информационная безопасность",
        bgColor: "bg-security",
        textColor: "text-security",
        items: [],
      },
      {
        link: "service-packages",
        title: "Пакеты услуг",
        bgColor: "bg-f1-light",
        textColor: "text-f1-light",
        items: [],
      },
    ],
  },
  {
    link: "portfolio",
    title: "Портфолио",
    bgColor: "bg-cloud",
    textColor: "text-cloud",
    items: [],
  },
  {
    link: "experts",
    title: "Эксперты",
    bgColor: "bg-security",
    textColor: "text-security",
    items: [],
  },
  {
    link: "blog",
    title: "Блог",
    bgColor: "bg-alert",
    textColor: "text-alert",
    items: [],
  },
  {
    link: "contacts",
    title: "Контакты",
    bgColor: "bg-gray-100",
    textColor: "text-white",
    items: [],
  },
];
